name: quiz_app
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.2
  toggle_switch: ^1.4.0
  fluttertoast: ^8.0.8
  get_it: ^3.0.3
  http: ^0.12.0+2
  lite_rolling_switch: ^0.1.1

  # icons
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/